version: '3'
services:
  iaww:
    build: .
    restart: always
    image: iaww/main
    container_name: iaww
    depends_on:
    - iaww-letsencrypt
    ports:
      - 8080:8080
    volumes:
      - "/etc/iaww/db:/app/db"
  iaww-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: iaww-letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/iaww/wonderfull/nginx/default:/config/nginx/site-confs/default"
      - "/iaww/letsencrypt:/config"
    environment:
      - EMAIL=guillaume.andres@yahoo.fr 
      - URL=astek-iaww.ddns.net
      - VALIDATION=http
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - STAGING=false
    
